// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXd4IZm5-vfEgwxjJka1N8RRech-1oylU',
    appId: '1:296031466051:web:066bfcdac67a63fd76daf6',
    messagingSenderId: '296031466051',
    projectId: 'visitlog00',
    authDomain: 'visitlog00.firebaseapp.com',
    storageBucket: 'visitlog00.appspot.com',
    measurementId: 'G-8X0Z9WS1EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5IVwqAhCZgKo1kB4kUv-ToTZjOWQOyQg',
    appId: '1:296031466051:android:2f896b4ec912b10a76daf6',
    messagingSenderId: '296031466051',
    projectId: 'visitlog00',
    storageBucket: 'visitlog00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxOfaUzbr-88IgQN5VvMfSWVON9nAKuVY',
    appId: '1:296031466051:ios:9ff73a25293568b176daf6',
    messagingSenderId: '296031466051',
    projectId: 'visitlog00',
    storageBucket: 'visitlog00.appspot.com',
    androidClientId: '296031466051-8hd70bofuengtk3urm8sf2fh8vcc8hhr.apps.googleusercontent.com',
    iosClientId: '296031466051-904qmvontf3g840mnend7n8hc41u45ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.visitlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxOfaUzbr-88IgQN5VvMfSWVON9nAKuVY',
    appId: '1:296031466051:ios:12114ffbf556c3aa76daf6',
    messagingSenderId: '296031466051',
    projectId: 'visitlog00',
    storageBucket: 'visitlog00.appspot.com',
    androidClientId: '296031466051-8hd70bofuengtk3urm8sf2fh8vcc8hhr.apps.googleusercontent.com',
    iosClientId: '296031466051-k7v2ieq5148o473cfijap77380tmlmml.apps.googleusercontent.com',
    iosBundleId: 'com.example.visitlog.RunnerTests',
  );
}
